apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-deploy
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling-deploy
  targetCPUUtilizationPercentage: 70